### ISSUE TITLE
Bei @Review mit 'arthistdate' wird das Jahr jetzt in Klammern gesetzt

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory-bonn#38]
Vermutlich ein Artefakt von https://github.com/LukasCBossert/biblatex-arthistory/commit/f0aea20d97dbfccd3fc9fb1ea7f55a0f7708cf2c

**Comment by LukasCBossert** [comment]
hm, ich denke auch - es soll wohl so nicht sein :) 

man müsste also eine Abfrage einbauen, ob `arthistdate` definiert ist und dann keine Klammer um das Jahr!?
