### ISSUE TITLE
Option `endpages` produziert neuerdings Fehler

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory-bonn#40]
Neuerdings (vielleicht seit dem letzten `biblatex` update?) produziert die Option `endpages` einen fatalen Fehler:
```
/usr/local/texlive/2016/texmf-dist/tex/latex/biblatex/biblatex.sty:13053: Package keyval Error: endpages undefined. [\blx@processoptions]
```

**Comment by LukasCBossert** [comment]
Was sollte mit `endpages` passieren? Die Option ist nicht angelegt. Oder meintest du `enddot` ?

**Comment by AlfonsoMuskedunder** [comment]
Typical me. Hätte ich einfach nur in die _eigene_ Dokumentation reingeschaut, hätte ich erfahren können, dass die Option jetzt `pagesfull` heißt. #I'llseemyselfout

**Comment by LukasCBossert** [comment]
:-) ok
