### ISSUE TITLE
Doktorarbeiten, die nicht in Verlag erschienen sind (@Phdthesis, @Thesis)...

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory-bonn#43]
...werden seltsam ausgegeben.

Am Beispiel `May2011` im file `test.tex`:
```
May, Rose Marie: The Church of San Giacomo degli Spagnoli and the Formation of Spanish Identity in Sixteenth Century Rome, (zugl. Temple University, Diss.).
```

1. Das "zugl." ist hier ganz fehl am Platze.
2. Am besten ließe man hier die Klammern weg, also `...Sixteenth Century Rome, Temple University, Diss., 2011.`
3. Das Feld `year`/`date` sollte nicht ignoriert werden.

All dies dürften Überbleibsel der Integration von Dissertationen in die "normale" `@book`-Klasse sein - es wäre super, beides ohne Reibungsverluste trennen zu können...

**Comment by LukasCBossert** [comment]
Kannst du ein MWE dazu erstellen mit dem bibtex-Eintrag? 

>1. geht das aus dem Leitfaden hervor? Warum ist es fehl am Platz?

>2. Ließe man die Klammern weg, wäre es wiederum uneinheitlich, oder?

> 3. Ja, Das Datum sollte dennoch ausgegeben werden. wird es "eigentlich" `\printthesisdate` (https://github.com/LukasCBossert/biblatex-arthistory-bonn/blob/master/arthistory-bonn.bbx#L440) 

> All dies dürften Überbleibsel der Integration von Dissertationen in die "normale" @book-Klasse sein - es wäre super, beides ohne Reibungsverluste trennen zu können... 

Aber Dissertationen sind doch mit `@thesis`/`@phdthesis` angelegt?

**Comment by AlfonsoMuskedunder** [comment]
Ich habe ein MWE commited, die Datei `test.tex`.

Die Arbeit, die du bislang in Dissertationen gesteckt hattest, bezog sich auf jene, die später als Buch einen Verlag gefunden haben; siehe z.B. `Kanz2002` im MWE. Hier hat man ein "normales" `@book` und macht zusätzlich in einer Klammer kenntlich, dass das Buch nahezu ganz oder in weiten teilen (dann eben `zugl.`) identisch ist mit der Dissertation. Dies ist auch der einzige Fall, der im Leitfaden abgehandelt wird.

Die Standard-entry-types `@thesis` etc. haben aber auch ihre Berechtigung; da manche Dissertationen eben nicht in einem Verlag veröffentlicht wurden. Da man dann nicht vom Verlagstitel ablenkt, wäre es aus unserer Sicht auch OK, die Angaben zur Diss. nicht in einer Klammer zu "verstecken".

**Comment by AlfonsoMuskedunder** [comment]
Zu 3: Du hattest ein zusätzliches Feld `dissdate` erstellt, um zwischen dem Veröffentlichungsjahr des Buchs im Verlag und dem Jahr der Disputation unterscheiden zu können; mir scheint, dass fälschlicherweise die eigentlich gar nicht anvisierte Klasse `thesis`/`phdthesis` jetzt nur noch `dissdate` ausgibt.

**Comment by LukasCBossert** [comment]
Ich erinnere mich dunkel... wie schnell man die Details vergisst.

**Comment by LukasCBossert** [comment]
@AlfonsoMuskedunder Schau mal, ob der commit hierfür passt?

**Comment by AlfonsoMuskedunder** [comment]
Scheint zu funktionieren, danke!

(`dissdate` ist übrigens auch einer Umbennungsaktion zum Opfer gefallen und heißt mittlerweile `thesisdate`.)
