### ISSUE TITLE
biblatex 3.8

### ISSUE THREAD

**Issue by moewew** [LukasCBossert/biblatex-arthistory-bonn#44]
Die in https://github.com/LukasCBossert/biblatex-archaeologie/issues/113 angesprochenen Änderungen sind auch für diesen Stil relevant.

 - `extrayear` wird zu `extradate` und die Makronamen in den Standardstilen wurden dementsprechend angepasst.

https://github.com/LukasCBossert/biblatex-arthistory-bonn/blob/981dd370dfe6aa0f02050b60cca66e7d78d7c5e3/arthistory-bonn.cbx#L82

und 

https://github.com/LukasCBossert/biblatex-arthistory-bonn/blob/981dd370dfe6aa0f02050b60cca66e7d78d7c5e3/arthistory-bonn.cbx#L143-L147

sind betroffen.

**Comment by LukasCBossert** [comment]
Danke für die genaue Lokalisierung hier. Hatte schon befürchtet dass dieser Stil auch geändert werden muss.

**Comment by LukasCBossert** [comment]
Upload auf CTAN erfolgt.
