### ISSUE TITLE
Regression: In der Kurzzitation von Ausstellungskatalogen fehlt die Ortsangabe

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [LukasCBossert/biblatex-arthistory-bonn#46]
Anders als zu Zeiten von TeX Live 2016 wird die Ortsangabe in den Kurzzitationen von Ausstellungskatalogen - zumindest in TeX Live 2017 - nicht gedruckt.

Bei `Hani1983` wird statt `Ausst.-Kat. Zürich/Düsseldorf/Wien 1983` lediglich `Ausst.-Kat. 1983` ausgegeben.

Außerdem werden in der Vollzitation lediglich die Angaben zum *ersten* Ausstellungsort angezeigt.

Im Beispiel: Statt
`Der Hang zum Gesamtkunstwerk. Europäische Utopien seit 1800, hg. von Häni, Susanne /
Müller, Alois (Ausst.-Kat., Kunsthaus, 11. Februar bis 30. April 1983; Düsseldorf, Städtische Kunsthalle, 19. Mai bis 10. Juli 1983; Wien, Museum Moderner Kunst, 10. September bis 13. November 1983), Aarau u.a. 1983.`
wird
`Der Hang zum Gesamtkunstwerk. Europäische Utopien seit 1800, hg. von Häni, Susanne /
Müller, Alois (Ausst.-Kat., Kunsthaus, 11. Februar bis 30. April 1983), Aarau u.a. 1983.`
ausgegeben.

Hallo übrigens! :wave:

**Comment by LukasCBossert** [comment]
Hey!

Folgendes MWE 

```
\documentclass[ngerman]{scrartcl}
\usepackage{babel,csquotes}
\usepackage[
  backend=biber,
  style=arthistory-bonn,
 ]{biblatex}
\addbibresource{arthistory-bonn-examples.bib}

\begin{document}
\nocite{Hani1983}
\printbibliography
\end{document}
```

führt zu:

<img width="904" alt="bildschirmfoto 2019-02-27 um 21 47 34" src="https://user-images.githubusercontent.com/12896078/53521811-529f5a00-3ad9-11e9-95a4-5e0697990585.png">

Soweit ich sehe, stimmt alles?
TeXLive 2018 mit `latexmk -lualatex` übersetzt, tagesaktuelle Distribution.

**Comment by AlfonsoMuskedunder** [comment]
Ja, bei dir ist es korrekt.

Komisch... Hab es gerade in Overleaf mit den gängigen engines getestet, da klappt es auch stets. Und laut log nutzt der Dienst immer noch TeX Live 2017 - so wie ich zuhause. Vielleicht stimmt etwas nicht mit meiner Installation.

**Comment by LukasCBossert** [comment]
schau mal, welche biblatex/biber version bei dir genutzt wird.

**Comment by AlfonsoMuskedunder** [comment]
Mach ich. Hab übrigens gerade auch in Overleaf das vorige issue getestet, Klammern um die Jahreszahl bei Kurzzitationen von Artikeln - das ist hier ebenfalls kein Problem. :S

**Comment by LukasCBossert** [comment]
da hast du wohl eine komische TeXLive-Distribution?!

**Comment by AlfonsoMuskedunder** [comment]
Wir haben mal, auf meine Bitte hin, `exhibfirstvenue` zu `exhibfirstlocation` umdefiniert... :grimacing:
